import type { PersonResult } from "./types";

/**
 * Seeded demo talent pool standing in for a real people-search provider
 * (People Data Labs / Apollo.io / Proxycurl / Coresignal). The adapter
 * interface in `provider.ts` is provider-agnostic — swap in a real HTTP
 * client here without touching any UI or API route.
 *
 * Phone numbers use the NANP fictional block (555-0100 to 555-0199,
 * reserved by NANPA for exactly this purpose) so nothing here can ever
 * dial a real person by accident. Replace with a real, consented number
 * in the UI before triggering a live Hunar voice call.
 */
export const SEEDED_TALENT_POOL: Omit<PersonResult, "matchScore">[] = [
  {
    externalId: "seed-001",
    name: "Ananya Deshmukh",
    title: "Senior Machine Learning Infrastructure Engineer",
    company: "Meridian AI Labs",
    location: "Bengaluru, India",
    email: "ananya.deshmukh@example.com",
    phone: "+15550101",
    linkedinUrl: "https://linkedin.com/in/example-ananya-deshmukh",
    yearsExperience: 7,
    skills: ["Python", "PyTorch", "vLLM", "Kubernetes", "CUDA", "Distributed Training", "MLOps"],
    summary:
      "Leads training-infra for multi-billion parameter LLMs; built the internal model-serving platform on Kubernetes + vLLM.",
  },
  {
    externalId: "seed-002",
    name: "David K. Vance",
    title: "Staff Compiler Engineer",
    company: "CloudAI Systems",
    location: "Seattle, WA",
    email: "david.vance@example.com",
    phone: "+15550102",
    linkedinUrl: "https://linkedin.com/in/example-david-vance",
    yearsExperience: 11,
    skills: ["C++", "LLVM", "MLIR", "CUDA", "Compilers", "Performance Engineering"],
    summary: "MLIR/LLVM compiler engineer specializing in GPU kernel auto-tuning and PyTorch Dynamo/FX passes.",
  },
  {
    externalId: "seed-003",
    name: "Elena Rostova",
    title: "ML Systems Specialist",
    company: "Google DeepMind (ex)",
    location: "New York, NY",
    email: "elena.rostova@example.com",
    phone: "+15550103",
    linkedinUrl: "https://linkedin.com/in/example-elena-rostova",
    yearsExperience: 5,
    skills: ["FlashAttention", "Triton", "CUDA", "PyTorch", "vLLM", "Research Engineering"],
    summary: "Ex-DeepMind research engineer; shipped FlashAttention-2 kernel optimizations to production inference stack.",
  },
  {
    externalId: "seed-004",
    name: "Marcus Sterling",
    title: "Zero-Copy I/O Systems Architect",
    company: "Vantage Cloud",
    location: "Boston, MA",
    email: "marcus.sterling@example.com",
    phone: "+15550104",
    yearsExperience: 9,
    skills: ["Rust", "io_uring", "Distributed Systems", "Storage Engines", "Networking"],
    summary: "Built a zero-copy storage engine handling 40GB/s sustained throughput for a multi-tenant data platform.",
  },
  {
    externalId: "seed-005",
    name: "Priya Raghunathan",
    title: "Backend Engineer, Payments",
    company: "Stripewise",
    location: "Remote (India)",
    email: "priya.raghunathan@example.com",
    phone: "+15550105",
    yearsExperience: 4,
    skills: ["Node.js", "TypeScript", "PostgreSQL", "Payments", "Idempotency", "Kafka"],
    summary: "Owns the ledger and reconciliation service processing 2M+ transactions/day.",
  },
  {
    externalId: "seed-006",
    name: "Wei Chen",
    title: "Distributed Storage Lead",
    company: "Orbital Data",
    location: "Singapore",
    email: "wei.chen@example.com",
    phone: "+15550106",
    yearsExperience: 10,
    skills: ["Go", "Raft", "Distributed Storage", "Kubernetes Operators", "gRPC"],
    summary: "Led design of a Raft-based distributed KV store powering multi-region failover for a fintech platform.",
  },
  {
    externalId: "seed-007",
    name: "Sofia Marquez",
    title: "Product Designer, Growth",
    company: "Lattice Health",
    location: "Austin, TX",
    email: "sofia.marquez@example.com",
    phone: "+15550107",
    yearsExperience: 6,
    skills: ["Figma", "Design Systems", "User Research", "A/B Testing", "Prototyping"],
    summary: "Redesigned onboarding flow, lifting activation rate 22% across web and mobile.",
  },
  {
    externalId: "seed-008",
    name: "Julian Okafor",
    title: "Enterprise Account Executive",
    company: "Northwind SaaS",
    location: "Chicago, IL",
    email: "julian.okafor@example.com",
    phone: "+15550108",
    yearsExperience: 8,
    skills: ["Enterprise Sales", "SaaS", "Salesforce", "Negotiation", "Pipeline Management"],
    summary: "Consistently 130%+ of quota selling into Fortune 500 procurement and supply-chain teams.",
  },
  {
    externalId: "seed-009",
    name: "Hannah Lindqvist",
    title: "Growth Marketing Manager",
    company: "Fjord Analytics",
    location: "Stockholm, Sweden",
    email: "hannah.lindqvist@example.com",
    phone: "+15550109",
    yearsExperience: 5,
    skills: ["Growth Marketing", "SEO", "Paid Acquisition", "Lifecycle Marketing", "SQL"],
    summary: "Scaled organic + paid acquisition from 40k to 310k MAU in 18 months on a lean budget.",
  },
  {
    externalId: "seed-010",
    name: "Rahul Bhandari",
    title: "Site Reliability Engineer",
    company: "Continuum Cloud",
    location: "Pune, India",
    email: "rahul.bhandari@example.com",
    phone: "+15550110",
    yearsExperience: 6,
    skills: ["SRE", "Kubernetes", "Terraform", "Prometheus", "Incident Response", "AWS"],
    summary: "On-call lead for a 99.99% SLA platform; built the org's chaos-engineering test harness.",
  },
  {
    externalId: "seed-011",
    name: "Chidera Nwosu",
    title: "Data Scientist, Risk",
    company: "Ledger Financial",
    location: "Lagos, Nigeria",
    email: "chidera.nwosu@example.com",
    phone: "+15550111",
    yearsExperience: 4,
    skills: ["Python", "XGBoost", "Feature Engineering", "Credit Risk Modeling", "SQL"],
    summary: "Built the fraud-scoring model reducing chargeback losses by 31% year-over-year.",
  },
  {
    externalId: "seed-012",
    name: "Liam O'Connor",
    title: "Kernel Systems Developer",
    company: "Fenwick Semiconductor",
    location: "London, UK",
    email: "liam.oconnor@example.com",
    phone: "+15550112",
    yearsExperience: 12,
    skills: ["C", "Linux Kernel", "Device Drivers", "Real-Time Systems", "Embedded"],
    summary: "Upstream Linux kernel contributor; owns the NIC driver stack for a low-latency trading appliance.",
  },
  {
    externalId: "seed-013",
    name: "Mei Tanaka",
    title: "Frontend Platform Engineer",
    company: "Kioku Studio",
    location: "Tokyo, Japan",
    email: "mei.tanaka@example.com",
    phone: "+15550113",
    yearsExperience: 5,
    skills: ["React", "TypeScript", "Next.js", "Design Systems", "Web Performance"],
    summary: "Owns the shared component library consumed by 14 product teams; cut LCP by 40%.",
  },
  {
    externalId: "seed-014",
    name: "Tomás Alarcón",
    title: "Customer Success Lead",
    company: "Vela Robotics",
    location: "Mexico City, Mexico",
    email: "tomas.alarcon@example.com",
    phone: "+15550114",
    yearsExperience: 7,
    skills: ["Customer Success", "Onboarding", "Churn Analysis", "SaaS", "Account Management"],
    summary: "Reduced logo churn from 11% to 4% by restructuring the onboarding and QBR cadence.",
  },
  {
    externalId: "seed-015",
    name: "Fatima Al-Sayed",
    title: "Technical Recruiter",
    company: "Talenscape",
    location: "Dubai, UAE",
    email: "fatima.alsayed@example.com",
    phone: "+15550115",
    yearsExperience: 6,
    skills: ["Technical Recruiting", "Sourcing", "ATS", "Employer Branding", "Interview Design"],
    summary: "Built and scaled a 40-person engineering org in under 14 months at a Series B startup.",
  },
  {
    externalId: "seed-016",
    name: "Grace Muthoni",
    title: "DevOps Engineer",
    company: "Baobab Cloud",
    location: "Nairobi, Kenya",
    email: "grace.muthoni@example.com",
    phone: "+15550116",
    yearsExperience: 4,
    skills: ["DevOps", "CI/CD", "Docker", "Kubernetes", "GitHub Actions", "Terraform"],
    summary: "Cut deploy lead time from 45 minutes to under 6 by redesigning the CI/CD pipeline.",
  },
  {
    externalId: "seed-017",
    name: "Oskar Nowak",
    title: "Security Engineer",
    company: "Warden Systems",
    location: "Warsaw, Poland",
    email: "oskar.nowak@example.com",
    phone: "+15550117",
    yearsExperience: 8,
    skills: ["Application Security", "Penetration Testing", "Threat Modeling", "SOC2", "Python"],
    summary: "Led the SOC2 Type II readiness program and runs the internal red-team exercises.",
  },
  {
    externalId: "seed-018",
    name: "Isabela Ferreira",
    title: "Finance Operations Manager",
    company: "Cascata Logistics",
    location: "São Paulo, Brazil",
    email: "isabela.ferreira@example.com",
    phone: "+15550118",
    yearsExperience: 9,
    skills: ["FP&A", "Financial Modeling", "Operations", "Forecasting", "Excel/SQL"],
    summary: "Owns quarterly forecasting across a 100-location logistics network spanning 4 currencies.",
  },
  {
    externalId: "seed-019",
    name: "Noah Bergström",
    title: "Voice AI / Conversational Engineer",
    company: "Echofield",
    location: "Berlin, Germany",
    email: "noah.bergstrom@example.com",
    phone: "+15550119",
    yearsExperience: 5,
    skills: ["Speech Recognition", "TTS", "LLM Agents", "Python", "Real-time Audio", "Whisper"],
    summary: "Built low-latency ASR/TTS pipelines for a multilingual IVR product handling 2M calls/month.",
  },
  {
    externalId: "seed-020",
    name: "Aditi Kulkarni",
    title: "Principal Product Manager, Platform",
    company: "Northstar Cloud",
    location: "Hyderabad, India",
    email: "aditi.kulkarni@example.com",
    phone: "+15550120",
    yearsExperience: 10,
    skills: ["Product Strategy", "API Platforms", "Roadmapping", "Stakeholder Management"],
    summary: "Owns the developer platform PM function; shipped the public API program from 0 to 3,000 integrators.",
  },
  {
    externalId: "seed-021",
    name: "Ethan Brooks",
    title: "Full-Stack Engineer",
    company: "Ridgeline Health",
    location: "Denver, CO",
    email: "ethan.brooks@example.com",
    phone: "+15550121",
    yearsExperience: 3,
    skills: ["React", "Node.js", "PostgreSQL", "TypeScript", "REST APIs"],
    summary: "Shipped the patient-scheduling module end to end from design through production rollout.",
  },
  {
    externalId: "seed-022",
    name: "Camille Dubois",
    title: "Data Engineer",
    company: "Lumière Analytics",
    location: "Paris, France",
    email: "camille.dubois@example.com",
    phone: "+15550122",
    yearsExperience: 6,
    skills: ["Airflow", "dbt", "Spark", "Snowflake", "Python", "Data Modeling"],
    summary: "Rebuilt the core data warehouse on dbt + Snowflake, cutting pipeline runtime by 65%.",
  },
  {
    externalId: "seed-023",
    name: "Samuel Osei",
    title: "Operations Manager, Field Workforce",
    company: "Terra Mining Group",
    location: "Accra, Ghana",
    email: "samuel.osei@example.com",
    phone: "+15550123",
    yearsExperience: 11,
    skills: ["Workforce Operations", "Scheduling", "Field Logistics", "Compliance", "Reporting"],
    summary: "Runs shift scheduling and attendance compliance across 18 remote extraction sites.",
  },
  {
    externalId: "seed-024",
    name: "Yuki Sato",
    title: "AI Research Engineer",
    company: "Sora Robotics",
    location: "Osaka, Japan",
    email: "yuki.sato@example.com",
    phone: "+15550124",
    yearsExperience: 4,
    skills: ["PyTorch", "Reinforcement Learning", "Robotics", "Simulation", "Python"],
    summary: "Published 3 papers on sim-to-real transfer for warehouse robotics manipulation policies.",
  },
];
